name: Build Docker Images for Prod & Push to DockerHub

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Build Frontend
      run: |
        docker build -f Dockerfile.stage -t smirnovskoe/streamad_frontend:dev .
    - name: Docker Push Frontend
      run: |
        docker push smirnovskoe/streamad_frontend:dev  
